credentials:
  gcp: ""

velero:
  configuration:
    backupStorageLocation:
      - name: default
        default: true
        provider: gcp
        bucket: velero.home.anderssonfischer.com
        config:
          region: europe-north1
    volumeSnapshotLocation: []
    defaultVolumesToFsBackup: true

  credentials:
    useSecret: true
    existingSecret: velero-credentials

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      volumeMounts:
        - mountPath: /target
          name: plugins

  deployNodeAgent: true

  schedules:
    daily:
      schedule: "0 3 * * *"
      template:
        ttl: "336h"
        storageLocation: default
        includedNamespaces:
          - "*"
