test:
  credentials:
    gcp: ""

velero:
  configuration:
    backupStorageLocation:
      - name: default
        default: true
        provider: gcp
        bucket: velero.home.anderssonfischer.com
    volumeSnapshotLocation: []
    defaultVolumesToFsBackup: true

  credentials:
    useSecret: true
    existingSecret: velero-credentials

  initContainers:
    - name: velero-plugin-for-gcp
      image: velero/velero-plugin-for-gcp
      volumeMounts:
        - name: plugins
          mountPath: /target

  deployNodeAgent: true

  schedules:
    daily:
      schedule: "0 3 * * *"
      template:
        ttl: "336h"
        storageLocation: default
        includedNamespaces:
          - "*"
