apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ .Values.s3.username }}
    aws_secret_access_key={{ .Values.s3.password }}
