homeassistant: true
permit_join: false

mqtt:
  server: mqtt://mosquitto-service.home-assistant.svc.cluster.local:8883
  user: {{ .Values.mqtt.user }}
  password: {{ .Values.mqtt.password }}

serial:
  port: /dev/ttyACM0

frontend:
  port: 8080
