apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner
  namespace: gitea
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-runner-token
  namespace: gitea
  annotations:
    kubernetes.io/service-account.name: gitea-runner
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-runner-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-runner-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-runner-cluster-role
subjects:
  - kind: ServiceAccount
    name: gitea-runner
    namespace: gitea
