apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitea-runner-role
  namespace: gitea
rules:
  - apiGroups: ["traefik.io"]
    resources:
      - ingressroutetcps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-runner-binding
  namespace: gitea
subjects:
  - kind: ServiceAccount
    name: gitea-runner
    namespace: gitea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-runner-role
