apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.registry.server .Values.registry.username .Values.registry.password (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-certificates
  namespace: api
data:
  local.crt: |-
{{ .Values.certificates.local | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
stringData:
  private.pem: |-
{{ .Values.keys.private | nindent 4 }}
  public.pem: |-
{{ .Values.keys.public | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: application
          image: "{{ .Values.application.image }}"
          securityContext:
            privileged: true
          env:
            - name: PRIVATE_KEY_PATH
              value: /app/keys/private.pem
            - name: PUBLIC_KEY_PATH
              value: /app/keys/public.pem
            - name: LOCAL_CERTIFICATE_PATH
              value: /app/certs/local.crt
            - name: TESLA_VEHICLE_VIN
              value: "{{ .Values.tesla.vehicle.vin }}"
            - name: TESLA_WALL_CONNECTOR_HOST
              value: "{{ .Values.tesla.wallConnector.host }}"
          volumeMounts:
            - name: dbus
              mountPath: /run/dbus
            - name: keys
              mountPath: /app/keys
              readOnly: true
            - name: certificates
              mountPath: /app/certs
              readOnly: true
          ports:
            - containerPort: 3000
      volumes:
        - name: dbus
          hostPath:
            path: /run/dbus
        - name: keys
          secret:
            secretName: api-keys
            items:
              - key: private.pem
                path: private.pem
              - key: public.pem
                path: public.pem
        - name: certificates
          configMap:
            name: api-certificates
            items:
              - key: local.crt
                path: local.crt
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress-public
  namespace: api
spec:
  rules:
    - host: api.anderssonfischer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: api.anderssonfischer.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
