apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    per_listener_settings true

    log_dest stdout

    listener 8883
    protocol mqtt

    allow_anonymous false
    password_file /mosquitto/password/password.txt
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-password
  namespace: home-assistant
  labels:
    app: mosquitto
type: Opaque
stringData:
  password.txt: |
    {{ .Values.mosquitto.user }}:{{ .Values.mosquitto.passwordHash }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 8883
        - containerPort: 9001
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/
        - name: data
          mountPath: /mosquitto/data/
        - name: password
          mountPath: /mosquitto/password/
      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      - name: data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: password
        secret:
          secretName: mosquitto-password
          items:
            - key: password.txt
              path: password.txt
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  namespace: home-assistant
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - port: 8883
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto-ingress
  namespace: home-assistant
spec:
  rules:
  - host: mqtt.anderssonfischer.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mosquitto-service
            port:
              number: 8883
