application:
  image: ""

registry:
  server: ""
  username: ""
  password: ""

keys:
  private: ""
  public: ""

certificates:
  local: ""

tesla:
  vehicle:
    vin: ""
  wallConnector:
    host: ""
