enabled: true

giteaRootURL: https://gitea.anderssonfischer.com

existingSecret: "gitea-actions-token"
existingSecretKey: "token"

statefulset:
  actRunner:
    extraEnvs:
      - name: DOCKER_HOST
        value: tcp://localhost:2376
      - name: DOCKER_CERT_PATH
        value: /certs/client
      - name: DOCKER_TLS_VERIFY
        value: "1"
