enabled: true

giteaRootURL: https://gitea.anderssonfischer.com

existingSecret: "gitea-actions-token"
existingSecretKey: "token"

statefulset:
  actRunner:
    config: |-
      runner:
        capacity: 5
      container:
        valid_volumes:
          - /var/run/docker.sock
        options: -v /var/run/docker.sock:/var/run/docker.sock
